// cli/src/core/deployer.ts
// Stub — Phase 1 only supports --deploy local, which needs no additional action.
// Phase 3 will add AWS Terraform module copying.
export function deployLocal(): void {
  // No-op: docker-compose.yml is already generated by the composer
}
